### ISSUE TITLE
Replacement battery

### ISSUE THREAD

**Issue by adi-works** [Jamesits/sound-blaster-e5-battery#2]
I tracked Aliexpress for obtaining this battery and after a long period of unavailability, it's now available again. I'd rush to buy, because it may be gone again (current inventory is shy of 200 units). A&S are the vendors for this battery, but they only list on Alibaba and won't sell one-offs.

Get it [here](https://www.aliexpress.com/item/4000385583557.html).

**IMPORTANT**: If you replace the battery, make sure to upgrade the firmware ASAP, because they incorporated a battery management fix that should prevent from overcharging the battery.

**Comment by Jamesits** [comment]
Thanks for the information!

I found the same store on Taobao: https://item.taobao.com/item.htm?id=596660369313
Seems to be a lot cheaper (but IDK if they ship to overseas if purchased at Taobao).

**Comment by adi-works** [comment]
Nice find. I know Taobao, but failed to interact with that site before. I think it's more targeted at mainland China, but definitely worth a try.

Edit: I gave it a try, but shipping absolutely kills it, as it comes out 3x the cost of the battery, so it ends up being the same cost as Aliexpress.

**Comment by Jamesits** [comment]
Then I guess the high price on Aliexpress comes with a reason. I've added a link to this issue in the battery replacement doc, so closing this :)

**Comment by adi-works** [comment]
Great, I also posted about this on [Drop E5 listing](https://drop.com/buy/creative-sound-blaster-e5-usb-dac-amp-combo/talk#discussions) and [Youtube](https://www.youtube.com/watch?v=l1MhnLNRm88).

**Comment by silajim** [comment]
Hi!,
Just changed the battery of my E5, with the one of the listing (or a similar one). But I can't get it to charge seems like it's at 50% for 4 hours, or something like that.
Did it happen to someone else? I also connected the sensing yellow wire, not only the red and black

Nevermind... from the second light blinking in went to the third, seems it's working. It also seems I was just "used" to how fast the other battery "charged"
