### ISSUE TITLE
Add link to firmware update

### ISSUE THREAD

**Issue by adi-works** [Jamesits/sound-blaster-e5-battery#3]
I think we should add a link to [this](https://support.creative.com/Products/ProductDetails.aspx?catID=1118&catName=Amplifiers&subCatID=1122&prodID=22019&prodName=Sound%20Blaster%20E5).

That's the important fix that should prevent the battery from dying again:

> Device enters deep sleep power saving mode after more than 2 hours of idle time when connected to PC/Mac

**Comment by Jamesits** [comment]
I'm no expert on batteries, but sources show that the most important factor that contribute to a swollen battery is overcharging. I think shutting the device off (automatically or manually) will not help with that.

Feel free to correct me if I'm wrong.

**Comment by adi-works** [comment]
I'm not an expert either, but anything that can possibly help mitigate the issue is worth a try, plus, that firmware update fixes another issue. I don't think a mention and link would hurt.
