### ISSUE TITLE
How to test the battery?

### ISSUE THREAD

**Issue by adi-works** [Jamesits/sound-blaster-e5-battery#4]
My replacement battery from Aliexpress has finally arrived. Unfortunately, after soldering and hooking up everything it worked for a while and then I found out it doesn't take a charge and eventually (while trying different solutions) it got completely drained and now the E5 won't boot, it basically just flashes its leds abruptly like it's stuck in a boot loop or something. I have a multimeter so I tested the battery by attaching the red/black probes to the red/black wires and got no voltage read whatsoever, so it seems dead. However, I'm unsure whether I tested it correctly, maybe you can help with that? I want to make sure I tested it correctly before sending out an unfortunate dispute to Aliexpress.

**Comment by Jamesits** [comment]
Did you unsolder the battery or not during the voltage test or not? Plus there is a [recovery mode](https://github.com/Jamesits/sound-blaster-e5-battery#the-recovery-mode) where you can temporary stop the boot loop and make it charging for a while. (During charging the voltage between the battery +/- should be somewhere near 4.2v. )

**Comment by adi-works** [comment]
I unsoldered the three wires and then tested it. I tried charging it in recovery mode while it still had juice but no luck, it didn't charge.

**Comment by Jamesits** [comment]
I have no idea, normally it is impossible to measure zero voltage across a battery unless its protection circuit died.

**Comment by adi-works** [comment]
It's concluded to be dead then. I'll just have to get another battery.
