### ISSUE TITLE
The source of +5V

### ISSUE THREAD

**Issue by bamx23** [Jamesits/sound-blaster-e5-battery#5]
I've found a way to get +5V from micro-USB connection. It's a pretty tiny place to solder to, but all in all, it works well. I would also recommend filling this place with glue.
![IMG_3027](https://user-images.githubusercontent.com/443972/95324804-f43b7f80-08a8-11eb-8e4c-c37299dc9ac0.jpg)

**Comment by Jamesits** [comment]
Thank you for the info! I've appended it to the article.

**Comment by adi-works** [comment]
@bamx23 Do you have a picture of the entire implementation? I used @pbjacob implementation, but this seems cleaner. Btw, instead of soldering the resistor on a small piece of PCB, I soldered one of its legs directly to the top of the USB host connector casing, which makes for an easier, cleaner fix as you can use more tin, for a more robust solder.

**Comment by bamx23** [comment]
I don't have more images, but I've also just soldered a 10k resistor between GND and yellow bat cable. This +5V goes directly to red bat cable. That's all

**Comment by viktor-235** [comment]
I used @bamx23 implementation and took some photos. I used micro-usb casing as GND.

![PXL_20230402_130734595](https://user-images.githubusercontent.com/12280029/229453572-8ac78a3e-18ff-4102-8a3d-a7dbb7ddb6cb.jpg)

![PXL_20230402_132815472](https://user-images.githubusercontent.com/12280029/229453596-91ddf009-aa3c-4b54-a6b9-afc967e4a3b3.jpg)

**Comment by TheRealCodefather** [comment]
I want to try this on the SoundBlaster E3, board images are available here: https://www.head-fi.org/threads/creative-sound-blaster-e3-mod-adaptation.838371/
Any knowledge of someone trying this? my assumption is the no-battery hack could work the same way if using the +5V from the micro-USB port like @bamx23 did.
